---
- name: Build Linux kernel for SecureDrop.
  hosts: grsec-build-securedrop
  vars_prompt:
    - name: grsecurity_build_download_username
      prompt: "Username for grsecurity HTTP auth"
      # Warning: setting `private: no` for username entry
      # should cause the entered text to echo back, but
      # won't work when provisioning with Vagrant. See here:
      # https://github.com/mitchellh/vagrant/issues/2924
    - name: grsecurity_build_download_password
      prompt: "Password for grsecurity HTTP auth"
  roles:
    - role: build-grsec-kernel
      # Use 3.x stable kernel series for now, since we're running under Trusty.
      # Future versions of SecureDrop may depend on the 4.x series, in which case
      # the `stable2` patch type should be used.
      grsecurity_build_patch_type: stable
      grsecurity_build_custom_config: config-securedrop
      grsecurity_build_include_ubuntu_overlay: true
      # Bumping the revision from default "10" to "11" to ensure upgrades.
      grsecurity_build_revision: 3.14.79-grsec-11.00.Custom
      tags: kernel

      # Running the metapackage role *after* the build role is important,
      # because it depends on dynamic facts from the build role for determining
      # the appropriate kernel version, to set as dependencies.
    - role: build-grsec-metapackage
      grsecurity_metapackage_name: securedrop-grsec
      grsecurity_metapackage_kernel_version: 3.14.79
      # The SecureDrop project has already released a metapackage
      # based on Linux kenrel 3.14.79 (with grsecurity patches), so we must
      # bump the version number with a suffix to ensure apt priority.
      grsecurity_metapackage_kernel_version_suffix: r1
      tags: metapackage
