---
# Name of the metapackage created by this role.
grsecurity_metapackage_name: linux-grsec-metapackage

# Path to working directory for preparing build on target host.
grsecurity_metapackage_parent_directory: /tmp/build

# Version of the Linux kernel that was patched, reused as 'Version' in the
# control file for this metapackage. Provides meaningful semver for upgrades.
# The `build-grsec-kernel` role will dynamically define `linux_kernel_version`
# based on patch type selected. If the metapackage role is called in a different
# play, then the var won't be defined, so let's set it to a string in that case.
grsecurity_metapackage_kernel_version: "{{ linux_kernel_version|default('3.14.79') }}"

# Optional appended version for chaining versions, e.g. "3.14.79+0.0.1".
# Can be useful for shipping new versions of the metapackage without bumping
# the underlying dependencies.
grsecurity_metapackage_kernel_version_suffix: ''

# Architecture restriction for the control file for metapackage. Should match
# what was chosen in the build role.
grsecurity_metapackage_architecture: amd64

# Reusable vars for filepaths and filenames, so the built package can be fetched back
# to the Ansible controller.
grsecurity_metapackage_name_verbose: "{{ grsecurity_metapackage_name }}-{{ grsecurity_metapackage_kernel_version }}-{{ grsecurity_metapackage_architecture }}"
grsecurity_metapackage_build_directory: "{{ grsecurity_metapackage_parent_directory }}/{{ grsecurity_metapackage_name_verbose }}"

# Dict of sysctl options for inclusion in the metapackage. Used for managing SecureDrop
# sysctl values on production instances.
grsecurity_metapackage_sysctl_options:
  vm.heap_stack_gap: 1048576
